/// Shared helpers for the lib/services/* integration tests.
///
/// These tests run on a real device/emulator against the dedicated test
/// Supabase project. They do NOT pump the UI — they exercise the service
/// functions directly. Boot via:
///
///   flutter test integration_test/services \
///     --dart-define-from-file=tests/.env.test.json \
///     -d `device-id`
///
/// The JSON env file is generated by `npm --prefix tests run seed`.

library;

import 'package:integration_test/integration_test.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

const String supabaseUrl = String.fromEnvironment('SUPABASE_URL');
const String supabaseAnonKey = String.fromEnvironment('SUPABASE_ANON_KEY');

const String testTenantAEmail    = String.fromEnvironment('TEST_TENANT_A_EMAIL');
const String testTenantAPassword = String.fromEnvironment('TEST_TENANT_A_PASSWORD');
const String testTenantBEmail    = String.fromEnvironment('TEST_TENANT_B_EMAIL');
const String testTenantBPassword = String.fromEnvironment('TEST_TENANT_B_PASSWORD');
const String testLandlordEmail   = String.fromEnvironment('TEST_LANDLORD_EMAIL');
const String testLandlordPassword= String.fromEnvironment('TEST_LANDLORD_PASSWORD');

const String testTenantAId       = String.fromEnvironment('TEST_TENANT_A_ID');
const String testLandlordId      = String.fromEnvironment('TEST_LANDLORD_ID');
const String testListingId       = String.fromEnvironment('TEST_LISTING_ID');
const String testApplicationId   = String.fromEnvironment('TEST_APPLICATION_ID');
const String testContractId      = String.fromEnvironment('TEST_CONTRACT_ID');

bool _initialized = false;

/// Initialize the integration binding + Supabase exactly once per process.
/// Call from `setUpAll` in every spec file.
Future<void> ensureInitialized() async {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();
  if (_initialized) return;
  if (supabaseUrl.isEmpty || supabaseAnonKey.isEmpty) {
    throw StateError(
      'SUPABASE_URL / SUPABASE_ANON_KEY missing. Run `npm --prefix tests run seed` '
      'and pass --dart-define-from-file=tests/.env.test.json to flutter test.',
    );
  }
  await Supabase.initialize(url: supabaseUrl, anonKey: supabaseAnonKey);
  _initialized = true;
}

/// Sign in as the given seeded role. Returns the authenticated user id.
Future<String> signInAsTenantA() => _signIn(testTenantAEmail, testTenantAPassword);
Future<String> signInAsTenantB() => _signIn(testTenantBEmail, testTenantBPassword);
Future<String> signInAsLandlord() => _signIn(testLandlordEmail, testLandlordPassword);

Future<String> _signIn(String email, String password) async {
  final sb = Supabase.instance.client;
  await sb.auth.signOut();
  final res = await sb.auth.signInWithPassword(email: email, password: password);
  final id = res.user?.id;
  if (id == null) throw StateError('signIn failed for $email');
  return id;
}
